# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('station_name', models.CharField(max_length=400)),
                ('station_desc', models.CharField(max_length=800)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField(max_length=10)),
                ('location', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=800)),
                ('active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(default='DEFAULT_VALUE', max_length=100)),
                ('sensorOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SensorUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.SensorType')),
            ],
        ),
        migrations.CreateModel(
            name='UserSensorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.SensorDetail')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sensordetail',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.SensorType'),
        ),
        migrations.AddField(
            model_name='sensordetail',
            name='sensor_unit',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sensor_type', chained_model_field='sensor_type', on_delete=django.db.models.deletion.CASCADE, to='portal.SensorUnit'),
        ),
    ]
