# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_sensordetail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorunit',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='sensordetail',
            name='sensor_unit',
        ),
        migrations.DeleteModel(
            name='SensorUnit',
        ),
    ]
