# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20161205_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordetail',
            old_name='ip_address',
            new_name='container_id',
        ),
    ]
